name: Finance Project 1 - Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - run: npm install

      # 4. Optional: Build
      - run: npm run build || echo "No build script defined"

      # 5. Optional: Test
      - run: npm test || echo "No test script defined"
  
