name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Code checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run build (agar koi build step hai)
      - name: Build project
        run: npm run build || echo "No build script defined"

      # 5. Run tests (agar test script hai)
      - name: Run tests
        run: npm test || echo "No test script defined"

      # 6. (Optional) Lint or other checks
      - name: Lint check
        run: npm run lint || echo "No lint script defined"

